// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYnQkd2Bj1egSusr7uOuhVYq_RxIgYWwo',
    appId: '1:989735735941:web:9d60d28456a03fe9224fec',
    messagingSenderId: '989735735941',
    projectId: 'codlab3-25846',
    authDomain: 'codlab3-25846.firebaseapp.com',
    storageBucket: 'codlab3-25846.appspot.com',
    measurementId: 'G-EEM39JDJJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpFEOBnd3dIowUsfdHszvVvc3wSCOSPJk',
    appId: '1:989735735941:android:524630db69b10cff224fec',
    messagingSenderId: '989735735941',
    projectId: 'codlab3-25846',
    storageBucket: 'codlab3-25846.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuIQCZS_SjJTrE-rYZNnle2WRHISDywqE',
    appId: '1:989735735941:ios:bbe06895544477e4224fec',
    messagingSenderId: '989735735941',
    projectId: 'codlab3-25846',
    storageBucket: 'codlab3-25846.appspot.com',
    iosBundleId: 'com.codelabmodul3.codelabmodul3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuIQCZS_SjJTrE-rYZNnle2WRHISDywqE',
    appId: '1:989735735941:ios:bbe06895544477e4224fec',
    messagingSenderId: '989735735941',
    projectId: 'codlab3-25846',
    storageBucket: 'codlab3-25846.appspot.com',
    iosBundleId: 'com.codelabmodul3.codelabmodul3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYnQkd2Bj1egSusr7uOuhVYq_RxIgYWwo',
    appId: '1:989735735941:web:ce5505368466d942224fec',
    messagingSenderId: '989735735941',
    projectId: 'codlab3-25846',
    authDomain: 'codlab3-25846.firebaseapp.com',
    storageBucket: 'codlab3-25846.appspot.com',
    measurementId: 'G-2DQDNKQJV9',
  );
}
